# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadSecureFile@1
  displayName: 'download settings.xml for Maven'
  name: settingsxml
  inputs:
    secureFile: 'settings.xml'
    retryCount: '2'
#- task: CopyFiles@2
#  inputs:
#    SourceFolder: '${AGENT_TEMPDIRECTORY}'
#    Contents: '$(settingsxml.secureFilePath)'
#    TargetFolder: "${HOME}/.m2/"
#    OverWrite: true
- task: CmdLine@2
  inputs:
    script: 'cat $(settingsxml.secureFilePath)'
#- task: PowerShell@2
#  inputs:
#    targetType: 'inline'
#    script: |
#      Write-Output '$(settingsxml.secureFilePath)'
#      Write-Output '${HOME}'
#      Get-ChildItem -Path "${HOME}/.m2/" -Force -Recurse
##      Get-ChildItem env:
#- task: Maven@3
#  inputs:
#    mavenPomFile: 'pom.xml'
#    goals: 'clean install deploy'
#    publishJUnitResults: true
#    testResultsFiles: '**/surefire-reports/TEST-*.xml'
#    javaHomeOption: 'JDKVersion'
#    jdkVersionOption: '1.8'
#    mavenVersionOption: 'Default'
#    mavenOptions: '-Xmx3072m'
#    mavenAuthenticateFeed: true
#    effectivePomSkip: true
#    sonarQubeRunAnalysis: false