# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- develop

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: DownloadSecureFile@1
  displayName: 'download settings.xml for Maven'
  name: settingsxml
  inputs:
    secureFile: 'settingsxml'
    retryCount: '2'
- task: CopyFiles@2
  inputs:
    SourceFolder: '/home/vsts/work/_temp/'
    Contents: '$(settingsxml.secureFilePath)'
    TargetFolder: '${HOME}/.m2/'
    OverWrite: true
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      echo Installing $(settingsxml.secureFilePath) to ${home}/.m2/
      Copy-Item -Force "$(settingsxml.secureFilePath)" "${HOME}/.m2/"
      Get-ChildItem -Path ${HOME}/.m2/ -Force -Recurse
