# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  branches:
    include:
      - master
      - develop
      - release
      - features/*
  paths:
    include:
      - core/*
      - error/*
      - event/*
      - event-listener/*
      - pom.xml

pool:
  vmImage: 'ubuntu-latest'

variables:
  isToDeploy: $[and(ne(variables['Build.Reason'], 'PullRequest'), or(eq(variables['Build.SourceBranch'], 'refs/heads/master'), startsWith(variables['Build.SourceBranch'], 'refs/heads/release')))]

steps:
  - task: DownloadSecureFile@1
    displayName: 'download settings.xml for Maven'
    name: settingsxml
    inputs:
      secureFile: 'settings.xml'
      retryCount: '2'
  - task: Maven@3
    displayName: Build and Test
    condition: eq(variables.isToDeploy,false)
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'clean test'
      options: '-s $(settingsxml.secureFilePath) -DaltDeploymentRepository=cstar::default::https://pkgs.dev.azure.com/sia-dds/cstar/_packaging/cstar/maven/v1'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      codeCoverageToolOption: 'JaCoCo'
      codeCoverageClassFilter: '+:eu.sia.meda.**,-:**.*Config,-:**.*Scheduler,-:**.Dummy*,-:**.model.**,-:**.enums.**,-:**.*Constants,-:**.*Application,-:**.*Test,-:**.*Test.**,-:**Base*.**,-:ErrorManagerService.java'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      mavenVersionOption: 'Default'
      mavenOptions: '-Xmx3072m'
      mavenAuthenticateFeed: true
      effectivePomSkip: true
      sonarQubeRunAnalysis: false
  - task: Maven@3
    displayName: Build, Test and Deploy Artifacts
    condition: eq(variables.isToDeploy,true)
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'deploy'
      options: '-s $(settingsxml.secureFilePath) -DskipTests=true -DaltDeploymentRepository=cstar::default::https://pkgs.dev.azure.com/sia-dds/cstar/_packaging/cstar/maven/v1'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.8'
      mavenVersionOption: 'Default'
      mavenOptions: '-Xmx3072m'
      mavenAuthenticateFeed: true
      effectivePomSkip: true
      sonarQubeRunAnalysis: false
