/*
 * This file was automatically generated by EvoSuite
 * Fri Nov 22 23:37:06 GMT 2019
 */

package eu.sia.meda.exceptions.model;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

import java.util.List;

import org.junit.Test;

public class ErrorMessageTest {

	@Test
	public void test00() throws Throwable {
		ErrorMessage errorMessage0 = new ErrorMessage();
		errorMessage0.setSeverity("");
		String string0 = errorMessage0.getSeverity();
		assertEquals("", string0);
	}

	@Test
	public void test01() throws Throwable {
		ErrorMessage errorMessage0 = new ErrorMessage();
		errorMessage0.setMessageTitle("G\"faA");
		String string0 = errorMessage0.getMessageTitle();
		assertEquals("G\"faA", string0);
	}

	@Test
	public void test02() throws Throwable {
		ErrorMessage errorMessage0 = new ErrorMessage();
		errorMessage0.setMessageTitle("");
		String string0 = errorMessage0.getMessageTitle();
		assertEquals("", string0);
	}

	@Test
	public void test03() throws Throwable {
		ErrorMessage errorMessage0 = new ErrorMessage();
		errorMessage0.setMessageKey(";nP{Y3}Fz+><");
		String string0 = errorMessage0.getMessageKey();
		assertEquals(";nP{Y3}Fz+><", string0);
	}

	@Test
	public void test04() throws Throwable {
		ErrorMessage errorMessage0 = new ErrorMessage();
		errorMessage0.setMessageKey("");
		String string0 = errorMessage0.getMessageKey();
		assertEquals("", string0);
	}

	@Test
	public void test05() throws Throwable {
		ErrorMessage errorMessage0 = new ErrorMessage();
		errorMessage0.setMessage("EZW");
		String string0 = errorMessage0.getMessage();
		assertEquals("EZW", string0);
	}

	@Test
	public void test06() throws Throwable {
		ErrorMessage errorMessage0 = new ErrorMessage();
		errorMessage0.setMessage("");
		String string0 = errorMessage0.getMessage();
		assertEquals("", string0);
	}

	@Test
	public void test07() throws Throwable {
		ErrorMessage errorMessage0 = new ErrorMessage();
		errorMessage0.setLanguage("");
		String string0 = errorMessage0.getLanguage();
		assertEquals("", string0);
	}

	@Test
	public void test08() throws Throwable {
		ErrorMessage errorMessage0 = new ErrorMessage();
		errorMessage0.setErrorCode("EZW");
		String string0 = errorMessage0.getErrorCode();
		assertEquals("EZW", string0);
	}

	@Test
	public void test09() throws Throwable {
		ErrorMessage errorMessage0 = new ErrorMessage();
		errorMessage0.setErrorCode("");
		String string0 = errorMessage0.getErrorCode();
		assertEquals("", string0);
	}

	@Test
	public void test10() throws Throwable {
		ErrorMessage errorMessage0 = new ErrorMessage();
		errorMessage0.setMessageForm((MessageForm) null);
		assertNull(errorMessage0.getRetry());
	}

	@Test
	public void test12() throws Throwable {
		ErrorMessage errorMessage0 = new ErrorMessage();
		String string0 = errorMessage0.getMessage();
		assertNull(string0);
	}

	@Test
	public void test13() throws Throwable {
		ErrorMessage errorMessage0 = new ErrorMessage();
		errorMessage0.setSeverity("y~M <d");
		String string0 = errorMessage0.getSeverity();
		assertEquals("y~M <d", string0);
	}

	@Test
	public void test14() throws Throwable {
		ErrorMessage errorMessage0 = new ErrorMessage();
		String string0 = errorMessage0.getMessageTitle();
		assertNull(string0);
	}

	@Test
	public void test15() throws Throwable {
		ErrorMessage errorMessage0 = new ErrorMessage();
		errorMessage0.setLanguage("y~M <d");
		String string0 = errorMessage0.getLanguage();
		assertEquals("y~M <d", string0);
	}

	@Test
	public void test16() throws Throwable {
		ErrorMessage errorMessage0 = new ErrorMessage();
		String string0 = errorMessage0.getErrorCode();
		assertNull(string0);
	}

	@Test
	public void test17() throws Throwable {
		ErrorMessage errorMessage0 = new ErrorMessage();
		errorMessage0.setRetry((Boolean) null);
		assertNull(errorMessage0.getRetry());
	}

	@Test
	public void test18() throws Throwable {
		ErrorMessage errorMessage0 = new ErrorMessage();
		List<MessageForm> list0 = errorMessage0.getMessagesForm();
		assertNull(list0);
	}

	@Test
	public void test19() throws Throwable {
		ErrorMessage errorMessage0 = new ErrorMessage();
		Boolean boolean0 = errorMessage0.getRetry();
		assertNull(boolean0);
	}

	@Test
	public void test20() throws Throwable {
		ErrorMessage errorMessage0 = new ErrorMessage();
		String string0 = errorMessage0.getSeverity();
		assertNull(string0);
	}

	@Test
	public void test21() throws Throwable {
		ErrorMessage errorMessage0 = new ErrorMessage();
		String string0 = errorMessage0.getLanguage();
		assertNull(string0);
	}

	@Test
	public void test22() throws Throwable {
		ErrorMessage errorMessage0 = new ErrorMessage();
		String string0 = errorMessage0.getMessageKey();
		assertNull(string0);
	}

	@Test
	public void test23() throws Throwable {
		ErrorMessage errorMessage0 = new ErrorMessage();
		errorMessage0.setMessagesForm((List<MessageForm>) null);
		assertNull(errorMessage0.getMessage());
	}
}
