/*
 * This file was automatically generated by EvoSuite
 * Fri Nov 22 23:44:19 GMT 2019
 */

package eu.sia.meda.exceptions.model;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNull;

import org.junit.Test;

public class ArchRestDefaultSpringErrorTest {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ArchRestDefaultSpringError archRestDefaultSpringError0 = new ArchRestDefaultSpringError();
      archRestDefaultSpringError0.setTimestamp("9Th!2+w<9?F");
      String string0 = archRestDefaultSpringError0.getTimestamp();
      assertEquals("9Th!2+w<9?F", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      ArchRestDefaultSpringError archRestDefaultSpringError0 = new ArchRestDefaultSpringError();
      archRestDefaultSpringError0.setStatus("(>Ag3grv>yy}v&-NN=(");
      String string0 = archRestDefaultSpringError0.getStatus();
      assertEquals("(>Ag3grv>yy}v&-NN=(", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      ArchRestDefaultSpringError archRestDefaultSpringError0 = new ArchRestDefaultSpringError();
      archRestDefaultSpringError0.setPath("vD{|pfcaz64[");
      String string0 = archRestDefaultSpringError0.getPath();
      assertEquals("vD{|pfcaz64[", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      ArchRestDefaultSpringError archRestDefaultSpringError0 = new ArchRestDefaultSpringError();
      archRestDefaultSpringError0.setMessage("cQ,T97WQGkh=^");
      String string0 = archRestDefaultSpringError0.getMessage();
      assertEquals("cQ,T97WQGkh=^", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ArchRestDefaultSpringError archRestDefaultSpringError0 = new ArchRestDefaultSpringError();
      archRestDefaultSpringError0.setException("2OV ");
      String string0 = archRestDefaultSpringError0.getException();
      assertEquals("2OV ", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ArchRestDefaultSpringError archRestDefaultSpringError0 = new ArchRestDefaultSpringError();
      archRestDefaultSpringError0.setException("");
      String string0 = archRestDefaultSpringError0.getException();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ArchRestDefaultSpringError archRestDefaultSpringError0 = new ArchRestDefaultSpringError();
      archRestDefaultSpringError0.setError("");
      String string0 = archRestDefaultSpringError0.getError();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ArchRestDefaultSpringError archRestDefaultSpringError0 = new ArchRestDefaultSpringError();
      String string0 = archRestDefaultSpringError0.getStatus();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ArchRestDefaultSpringError archRestDefaultSpringError0 = new ArchRestDefaultSpringError();
      archRestDefaultSpringError0.setError("lgDHByMTx\"<#v");
      String string0 = archRestDefaultSpringError0.getError();
      assertEquals("lgDHByMTx\"<#v", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      ArchRestDefaultSpringError archRestDefaultSpringError0 = new ArchRestDefaultSpringError();
      String string0 = archRestDefaultSpringError0.getException();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      ArchRestDefaultSpringError archRestDefaultSpringError0 = new ArchRestDefaultSpringError();
      archRestDefaultSpringError0.setTimestamp("");
      String string0 = archRestDefaultSpringError0.getTimestamp();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      ArchRestDefaultSpringError archRestDefaultSpringError0 = new ArchRestDefaultSpringError();
      String string0 = archRestDefaultSpringError0.getTimestamp();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ArchRestDefaultSpringError archRestDefaultSpringError0 = new ArchRestDefaultSpringError();
      String string0 = archRestDefaultSpringError0.getError();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ArchRestDefaultSpringError archRestDefaultSpringError0 = new ArchRestDefaultSpringError();
      archRestDefaultSpringError0.setMessage("");
      String string0 = archRestDefaultSpringError0.getMessage();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      ArchRestDefaultSpringError archRestDefaultSpringError0 = new ArchRestDefaultSpringError();
      archRestDefaultSpringError0.setStatus("");
      String string0 = archRestDefaultSpringError0.getStatus();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      ArchRestDefaultSpringError archRestDefaultSpringError0 = new ArchRestDefaultSpringError();
      archRestDefaultSpringError0.setPath("");
      String string0 = archRestDefaultSpringError0.getPath();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      ArchRestDefaultSpringError archRestDefaultSpringError0 = new ArchRestDefaultSpringError();
      String string0 = archRestDefaultSpringError0.getPath();
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      ArchRestDefaultSpringError archRestDefaultSpringError0 = new ArchRestDefaultSpringError();
      String string0 = archRestDefaultSpringError0.getMessage();
      assertNull(string0);
  }
}
